
services:
  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tasksystem
      MYSQL_USER: root
      MYSQL_PASSWORD: qwerty
      MYSQL_ROOT_PASSWORD: qwerty
